export const CATEGORIES = [
  { id: 'mix', name: 'Campur', en: 'A bit of everything' },
  { id: 'food', name: 'Makan', en: 'Food & drink' },
  { id: 'geo', name: 'Peta', en: 'Geography' },
  { id: 'history', name: 'Sejarah', en: 'History' },
  { id: 'culture', name: 'Budaya', en: 'Culture & language' },
  { id: 'nature', name: 'Alam', en: 'Nature & wildlife' },
];

export const MODES = [
  { id: 'classic', name: 'Biasa', en: 'Classic', rule: '5 questions. Get 4 right to win a dish. The clock counts up, so try to beat your best time.' },
  { id: 'blitz', name: 'Kilat', en: 'Time attack', rule: '60 seconds on the clock. Every 5 correct answers wins a dish.' },
  { id: 'survival', name: 'Satu Nyawa', en: 'One life', rule: 'One wrong answer ends the run. Every 5 in a row wins a dish.' },
  { id: 'daily', name: 'Harian', en: 'Daily set', rule: 'Everyone gets the same 5 questions today. You get one try, and a pass guarantees a rare dish or better.' },
];

export const HINTS = [
  { id: 'fifty', name: '50 : 50', malay: 'Buang dua', price: 15, desc: 'Crosses out two wrong answers.' },
  { id: 'auntie', name: 'Ask Auntie', malay: 'Tanya makcik', price: 10, desc: 'The auntie at the next table votes. She is right about four times out of five.' },
  { id: 'clue', name: 'Clue', malay: 'Petunjuk', price: 8, desc: 'A small nudge in the right direction.' },
  { id: 'freeze', name: 'Freeze', malay: 'Beku masa', price: 12, desc: 'Stops the clock for 10 seconds.' },
  { id: 'skip', name: 'Skip', malay: 'Langkau', price: 20, desc: 'Swaps the question for a new one with no penalty.' },
];

export const RARITY = {
  common: { label: 'Biasa', en: 'Common' },
  rare: { label: 'Jarang', en: 'Rare' },
  epic: { label: 'Epik', en: 'Epic' },
  legendary: { label: 'Legenda', en: 'Legendary' },
};

export const DISHES = [
  { id: 'teh-tarik', name: 'Teh Tarik', rarity: 'common', price: 8, blurb: 'Pulled tea with a foamy crown.' },
  { id: 'roti-canai', name: 'Roti Canai', rarity: 'common', price: 10, blurb: 'Flaky flatbread and a bowl of dhal.' },
  { id: 'nasi-lemak', name: 'Nasi Lemak', rarity: 'common', price: 12, blurb: 'Coconut rice, sambal, egg, ikan bilis.' },
  { id: 'kuih-lapis', name: 'Kuih Lapis', rarity: 'common', price: 12, blurb: 'Nine layers, peeled one at a time.' },
  { id: 'satay', name: 'Satay', rarity: 'rare', price: 20, blurb: 'Charcoal skewers and peanut sauce.' },
  { id: 'cendol', name: 'Cendol', rarity: 'rare', price: 18, blurb: 'Shaved ice, pandan jelly, gula Melaka.' },
  { id: 'char-kway-teow', name: 'Char Kway Teow', rarity: 'rare', price: 22, blurb: 'Flat noodles with plenty of wok hei.' },
  { id: 'asam-laksa', name: 'Asam Laksa', rarity: 'rare', price: 25, blurb: 'Sour fish broth from Penang.' },
  { id: 'ikan-bakar', name: 'Ikan Bakar', rarity: 'epic', price: 38, blurb: 'Fish grilled on banana leaf.' },
  { id: 'durian', name: 'Musang King', rarity: 'legendary', price: 65, blurb: 'The king of fruits. Handle with care.' },
];

// c = category, o = options, a = index of the right option
export const QUESTIONS = [
  // ---------- food ----------
  { c: 'food', q: 'Which dish is often called Malaysia’s unofficial national dish?', o: ['Nasi Lemak', 'Nasi Goreng', 'Mee Rebus', 'Laksa Johor'], a: 0,
    clue: '"Lemak" means rich or creamy.', fact: 'The rice is cooked in coconut milk and pandan leaf, which is where the richness comes from.' },
  { c: 'food', q: 'What does "teh tarik" literally mean?', o: ['Iced tea', 'Pulled tea', 'Sweet tea', 'Morning tea'], a: 1,
    clue: 'Watch how the tea gets poured.', fact: 'It is poured back and forth between two jugs to cool it and build the foam.' },
  { c: 'food', q: 'Gula Melaka is traditionally made from…', o: ['Sugarcane', 'Sugar beet', 'Coconut palm sap', 'Wild honey'], a: 2,
    clue: 'It comes from a tree you see on every beach.', fact: 'The sap is boiled down over a fire, which gives it that smoky caramel taste.' },
  { c: 'food', q: 'Asam Laksa is most closely linked to which state?', o: ['Johor', 'Sabah', 'Kelantan', 'Penang'], a: 3,
    clue: 'The same island as George Town.', fact: 'Penang asam laksa is a sour broth of mackerel and tamarind.' },
  { c: 'food', q: '"Musang King" is a famous variety of…', o: ['Durian', 'Mango', 'Mangosteen', 'Rambutan'], a: 0,
    clue: 'You will not be allowed to take it on the train.', fact: 'Musang King (D197) is prized for its bitter-sweet, custardy yellow flesh.' },
  { c: 'food', q: 'Kaya, the classic toast spread, is made mostly from…', o: ['Peanuts', 'Coconut milk and eggs', 'Durian', 'Palm oil and cocoa'], a: 1,
    clue: 'It is a jam, but it is not made from fruit.', fact: 'Coconut milk, eggs and sugar are cooked slowly, often with pandan for colour.' },
  { c: 'food', q: 'Char kway teow is stir-fried…', o: ['Egg noodles', 'Glass noodles', 'Flat rice noodles', 'Rice vermicelli'], a: 2,
    clue: 'Flat, wide and white before it hits the wok.', fact: 'The smoky taste from a very hot wok is called "wok hei".' },
  { c: 'food', q: 'Ipoh is famous for which drink?', o: ['Milo Dinosaur', 'Sirap Bandung', 'Air Mata Kucing', 'White coffee'], a: 3,
    clue: 'The beans are roasted in margarine.', fact: 'Ipoh white coffee is roasted with palm-oil margarine and served with condensed milk.' },
  { c: 'food', q: 'What leaf is traditionally used to wrap nasi lemak?', o: ['Banana leaf', 'Pandan leaf', 'Lotus leaf', 'Curry leaf'], a: 0,
    clue: 'Big, green and folded into a pyramid.', fact: 'The warm rice picks up a light aroma from the leaf. The wrapped takeaway version is called "nasi lemak bungkus".' },
  { c: 'food', q: 'Roti canai is usually served with…', o: ['Kaya', 'Dhal or curry', 'Soy sauce', 'Peanut sauce'], a: 1,
    clue: 'Something you dip it into, often yellow.', fact: 'You tear the roti by hand and dip it. Ask for "banjir" to get it flooded in gravy.' },

  // ---------- geography ----------
  { c: 'geo', q: 'What is the capital city of Malaysia?', o: ['Putrajaya', 'Kuala Lumpur', 'George Town', 'Johor Bahru'], a: 1,
    clue: 'Its name means "muddy confluence".', fact: 'Kuala Lumpur is the capital. Most of the government sits in Putrajaya.' },
  { c: 'geo', q: 'Which city is the federal administrative centre?', o: ['Shah Alam', 'Ipoh', 'Putrajaya', 'Melaka'], a: 2,
    clue: 'A planned city, south of KL, named after the first prime minister.', fact: 'Putrajaya took over as the administrative centre in 1999.' },
  { c: 'geo', q: 'What is the highest mountain in Malaysia?', o: ['Gunung Tahan', 'Gunung Mulu', 'Cameron Highlands', 'Mount Kinabalu'], a: 3,
    clue: 'It is in Sabah.', fact: 'Mount Kinabalu is about 4,095 m high, and climbers usually aim to reach the top at sunrise.' },
  { c: 'geo', q: 'How many states does Malaysia have?', o: ['13', '11', '14', '16'], a: 0,
    clue: 'Count the stripes on the flag and subtract one.', fact: 'There are 13 states and 3 federal territories: Kuala Lumpur, Putrajaya and Labuan.' },
  { c: 'geo', q: 'Peninsular Malaysia and Malaysian Borneo are separated by the…', o: ['Andaman Sea', 'South China Sea', 'Java Sea', 'Strait of Malacca'], a: 1,
    clue: 'A big sea to the east of the peninsula.', fact: 'At the closest point, the two halves are about 600 km apart across the South China Sea.' },
  { c: 'geo', q: 'George Town is on which island?', o: ['Langkawi', 'Tioman', 'Penang', 'Pangkor'], a: 2,
    clue: 'Famous for street art and asam laksa.', fact: 'George Town’s historic centre has been a UNESCO World Heritage Site since 2008, shared with Melaka.' },
  { c: 'geo', q: 'Which is the largest Malaysian state by area?', o: ['Pahang', 'Sabah', 'Perak', 'Sarawak'], a: 3,
    clue: 'The Land of the Hornbills.', fact: 'Sarawak covers about 124,000 km², which is close to the size of all of Peninsular Malaysia.' },
  { c: 'geo', q: 'What is the longest river in Malaysia?', o: ['Rajang River', 'Pahang River', 'Kinabatangan River', 'Perak River'], a: 0,
    clue: 'It flows through Sarawak.', fact: 'The Rajang is about 560 km long.' },
  { c: 'geo', q: 'Langkawi belongs to which state?', o: ['Perlis', 'Kedah', 'Penang', 'Perak'], a: 1,
    clue: 'The rice bowl of Malaysia.', fact: 'Langkawi is an archipelago of 99 islands off the coast of Kedah.' },
  { c: 'geo', q: 'Malaysia shares the island of Borneo with…', o: ['Philippines only', 'Thailand and Brunei', 'Indonesia and Brunei', 'Indonesia only'], a: 2,
    clue: 'One giant neighbour and one small sultanate.', fact: 'Borneo is the third-largest island in the world and is split between three countries.' },

  // ---------- history ----------
  { c: 'history', q: 'In which year did Malaya gain independence?', o: ['1945', '1963', '1965', '1957'], a: 3,
    clue: 'Twelve years after World War II ended.', fact: 'Independence was declared on 31 August 1957 at Stadium Merdeka in Kuala Lumpur.' },
  { c: 'history', q: 'What word was shouted seven times at the declaration of independence?', o: ['Merdeka!', 'Malaysia!', 'Bersatu!', 'Hidup!'], a: 0,
    clue: 'The word means "freedom".', fact: 'Tunku Abdul Rahman led the crowd in shouting "Merdeka!" seven times.' },
  { c: 'history', q: 'Malaysia Day, when Malaysia was formed in 1963, is celebrated on…', o: ['31 August', '16 September', '1 February', '9 July'], a: 1,
    clue: 'Two weeks after Merdeka Day, but six years later.', fact: 'On 16 September 1963, Malaya, Sabah, Sarawak and Singapore joined to form Malaysia.' },
  { c: 'history', q: 'Who was Malaysia’s first prime minister?', o: ['Mahathir Mohamad', 'Abdul Razak Hussein', 'Tunku Abdul Rahman', 'Hussein Onn'], a: 2,
    clue: 'Known as the "Father of Independence".', fact: 'Tunku Abdul Rahman served from 1957 to 1970.' },
  { c: 'history', q: 'Which state left Malaysia in 1965 to become an independent country?', o: ['Brunei', 'Sabah', 'Sarawak', 'Singapore'], a: 3,
    clue: 'Today it is a city-state at the southern tip of the peninsula.', fact: 'Singapore separated on 9 August 1965.' },
  { c: 'history', q: 'Who founded the Melaka Sultanate around 1400?', o: ['Parameswara', 'Hang Tuah', 'Sultan Mansur Shah', 'Raja Iskandar'], a: 0,
    clue: 'A prince who came from Temasek, which is now Singapore.', fact: 'Legend says he named the city after the Melaka tree he was resting under.' },
  { c: 'history', q: 'The Portuguese captured Melaka in…', o: ['1402', '1511', '1641', '1824'], a: 1,
    clue: 'Early 16th century.', fact: 'Afonso de Albuquerque took the city in 1511. The Dutch then took it in 1641.' },
  { c: 'history', q: 'The Petronas Twin Towers were the world’s tallest buildings from…', o: ['1990 to 1995', '2004 to 2010', '1998 to 2004', '2010 to 2015'], a: 2,
    clue: 'Until Taipei 101 was finished.', fact: 'At 452 m they held the title until 2004, and they are still the tallest twin towers.' },
  { c: 'history', q: 'How often is Malaysia’s king, the Yang di-Pertuan Agong, chosen?', o: ['Every year', 'For life', 'Every 10 years', 'Every 5 years'], a: 3,
    clue: 'Same length as a typical parliament term.', fact: 'The nine Malay rulers take turns. It is a rotating monarchy, which is very rare.' },
  { c: 'history', q: 'What is the name of the Malaysian flag?', o: ['Jalur Gemilang', 'Sang Saka', 'Bendera Merdeka', 'Bulan Bintang'], a: 0,
    clue: 'It means "Stripes of Glory".', fact: 'Its 14 stripes stand for the 13 states and the federal government.' },

  // ---------- culture ----------
  { c: 'culture', q: 'What is Malaysia’s national language?', o: ['English', 'Bahasa Melayu', 'Tamil', 'Mandarin'], a: 1,
    clue: 'Also called Bahasa Malaysia.', fact: 'English, Mandarin, Tamil and dozens of indigenous languages are widely spoken too.' },
  { c: 'culture', q: 'What is Malaysia’s national flower?', o: ['Orchid', 'Jasmine', 'Hibiscus', 'Lotus'], a: 2,
    clue: 'It is known locally as "bunga raya".', fact: 'Its five petals stand for the five principles of the Rukun Negara.' },
  { c: 'culture', q: '"Terima kasih" means…', o: ['Good morning', 'Excuse me', 'See you later', 'Thank you'], a: 3,
    clue: 'You say it to the uncle when he hands over your teh tarik.', fact: 'The polite reply is "sama-sama", which means "you’re welcome".' },
  { c: 'culture', q: 'The traditional moon kite from Kelantan is called…', o: ['Wau bulan', 'Gasing', 'Sepak raga', 'Congkak'], a: 0,
    clue: 'It appears on the 50 sen coin.', fact: 'Wau bulan kites can be over 2 m wide and are hand-painted with floral patterns.' },
  { c: 'culture', q: 'Which festival of lights do Malaysian Hindus celebrate?', o: ['Thaipusam', 'Deepavali', 'Pongal', 'Vesak'], a: 1,
    clue: 'Oil lamps, kolam patterns and murukku.', fact: 'Deepavali is a public holiday, and many families hold open houses.' },
  { c: 'culture', q: 'During festivals, Malaysians often invite everyone over for…', o: ['Kenduri kahwin', 'Pasar malam', 'Rumah terbuka', 'Gotong-royong'], a: 2,
    clue: 'It translates as "open house".', fact: 'Friends of every background drop in for food during Raya, CNY, Deepavali and Christmas.' },
  { c: 'culture', q: 'What is the Malaysian currency called?', o: ['Rupiah', 'Baht', 'Peso', 'Ringgit'], a: 3,
    clue: 'RM for short.', fact: '"Ringgit" originally meant "jagged", after the serrated edges of old Spanish silver dollars.' },
  { c: 'culture', q: 'What does "makan" mean?', o: ['To eat', 'To drink', 'To cook', 'To buy'], a: 0,
    clue: 'This whole game is built around it.', fact: '"Dah makan?" ("Have you eaten?") is a common way to say hello.' },
  { c: 'culture', q: 'Gasing is a traditional game played with…', o: ['Kites', 'Spinning tops', 'Rattan balls', 'Seeds on a board'], a: 1,
    clue: 'It is wound with a rope and thrown.', fact: 'Expert gasing spinners can keep a top going for over an hour.' },
  { c: 'culture', q: 'Batik is made by drawing patterns on cloth with…', o: ['Ink', 'Thread', 'Hot wax', 'Chalk'], a: 2,
    clue: 'The drawn areas resist the dye.', fact: 'Malaysian batik often shows large flowers and leaves rather than animals or people.' },

  // ---------- nature ----------
  { c: 'nature', q: 'Rafflesia, found in Malaysia, is famous for being…', o: ['The smallest orchid', 'Edible', 'Blue', 'The largest single flower'], a: 3,
    clue: 'It can be about 1 m across.', fact: 'It smells of rotting meat to attract flies. That is why it is nicknamed the "corpse flower".' },
  { c: 'nature', q: 'What is Malaysia’s national animal?', o: ['Malayan tiger', 'Orangutan', 'Hornbill', 'Sun bear'], a: 0,
    clue: 'It appears on the coat of arms, twice.', fact: 'Fewer than 150 are thought to remain in the wild, so it is critically endangered.' },
  { c: 'nature', q: 'Where do wild orangutans live in Malaysia?', o: ['Cameron Highlands', 'Sabah and Sarawak', 'Langkawi', 'Taman Negara'], a: 1,
    clue: 'Only on the big island.', fact: '"Orang utan" is Malay for "person of the forest".' },
  { c: 'nature', q: 'The proboscis monkey of Borneo is known for its…', o: ['Blue face', 'Long tail', 'Huge nose', 'Loud song'], a: 2,
    clue: 'Proboscis means a long snout.', fact: 'Males with bigger noses have louder calls, and females seem to prefer them.' },
  { c: 'nature', q: 'Sarawak is nicknamed the Land of the…', o: ['Tigers', 'Orchids', 'Turtles', 'Hornbills'], a: 3,
    clue: 'A big bird with a helmet-like beak.', fact: 'Eight hornbill species live in Sarawak. The rhinoceros hornbill is the state bird.' },
  { c: 'nature', q: 'Gunung Mulu National Park is known worldwide for its…', o: ['Giant caves', 'Volcano', 'Coral reefs', 'Tea farms'], a: 0,
    clue: 'Look underground.', fact: 'Mulu’s Sarawak Chamber is one of the largest known cave chambers on Earth.' },
  { c: 'nature', q: 'Cameron Highlands is best known for…', o: ['Durian orchards', 'Tea plantations', 'Oil fields', 'Mangroves'], a: 1,
    clue: 'Cool air, rolling green hills.', fact: 'The BOH tea estate there has been growing tea since 1929.' },
  { c: 'nature', q: 'Sipadan Island in Sabah is world-famous for…', o: ['Surfing', 'Rock climbing', 'Scuba diving', 'Bird watching'], a: 2,
    clue: 'The action happens underwater.', fact: 'Its reef wall drops about 600 m, and turtles are everywhere.' },
  { c: 'nature', q: 'Taman Negara is believed to be one of the world’s oldest…', o: ['Deserts', 'Glaciers', 'Volcanoes', 'Rainforests'], a: 3,
    clue: 'It is green, wet and very old.', fact: 'The forest is estimated to be around 130 million years old.' },
  { c: 'nature', q: 'Kinabalu Park, a UNESCO site, is in which state?', o: ['Sabah', 'Sarawak', 'Pahang', 'Perak'], a: 0,
    clue: 'It is named after the mountain.', fact: 'It was Malaysia’s first UNESCO World Heritage Site, in 2000, alongside Mulu.' },
];
